#!/bin/bash

export DISPLAY=:0
export PATH=/home/usr/bin/auto-login:/usr/bin:/usr/sbin

target_host="sysdev.loongson.cn"

ping -c 1 -w 3 $target_host > /dev/null 2>&1

if [ $? -ne 0 ]; then
  echo "AutoLogin: "
  date
  autologin
fi
